/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Example 3:
Input: s = "a", t = "aa"
Output: "a"

Example 4:
Input: s = "ae", t = "aea"
Output: "a"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.
*/

import java.util.HashMap;

public class FindTheDifference 
{
	public char findTheDifference(String s, String t) 
	{
		HashMap<Character, Integer> map = new HashMap<Character, Integer>();
		int i, index = 0;
		
		for (i = 0; i < s.length(); i++)
			if (map.containsKey(s.charAt(i)))
				map.replace(s.charAt(i), map.get(s.charAt(i)) + 1);
			else
				map.put(s.charAt(i), 1);
		
		for (i = 0; i < t.length(); i++)
			if (map.containsKey(t.charAt(i)))
				map.replace(t.charAt(i), map.get(t.charAt(i)) + 1);
			else
				map.put(t.charAt(i), 1);
		
		for (i = 0; i < t.length(); i++)
		{
			if (map.get(t.charAt(i)) % 2 != 0)
			{
				index = i;				
				break;
			}
		}
		return t.charAt(index);
	}
}
